package com.consejo.enumeraciones;

public enum CircuitoExpediente {

	INGRESO,
	OFICINA_PARLAMENTARIA,
	COMISION_DE_GOBIERNO_Y_DESARROLLO_SOCIAL,
	COMISION_DE_DESARROLLO_URBANO_AMBIENTAL_Y_ECONOMIA,
	AMBAS_COMISIONES,
	ARCHIVO,
	PRESIDENCIA,
	BLOQUE_A,
	BLOQUE_B,
	BLOQUE_C,
	TODOS_LOS_BLOQUES,
	DESPACHOS_DE_COMISION,
	LEGISLACION,  //fin
	NOTAS_DE_COMISION,
	REPUESTA_AL_CIUDADANO, //fin
	NOTA_AL_MUNICIPIO,
	REPUESTA_DEL_MUNICIPIO,
	FIN,
	
}